export class Feedbackquestion{
    q1:string;
    a1:string;
    q2:string;
    a2:string;
    q3:string;
    a3:string;
    q4:string;
    a4:string;
    q5:string;
    a5:string;
    q6:string;
    a6:string;
    q7:string;
    a7:string;
    q8:string;
    a8:string;
    q9:string;
    a9:string;
    q10:string;
    a10:string;
    suggestion:string;
}