export class Roles {
    _id?: string;
    name: string;
    permission: Rolespermission;
    editable: boolean;
}

export class Rolespermission {
    recordedcourse: {
        addforself?: boolean;
        addforothers?: boolean;
        updateforself?: boolean;
        updateforothers?: boolean;
        view?: boolean;
        approve?: boolean;
        delete?: boolean;
    };
    livecourse: {
        addforself?: boolean;
        addforothers?: boolean;
        updateforself?: boolean;
        updateforothers?: boolean;
        view?: boolean;
        approve?: boolean;
        delete?: boolean;
    };
    coursebundle: {
        add?: boolean;
        update?: boolean;
        view?: boolean;
        approve?: boolean;
        delete?: boolean;
    };
    questionset: {
        addforself?: boolean;
        addforothers?: boolean;
        updateforself?: boolean;
        updateforothers?: boolean;
        view?: boolean;
        approve?: boolean;
        delete?: boolean;
    };
    schedule: {
        add?: boolean;
        update?: boolean;
        view?: boolean; //view all
        viewown?: boolean;
        export?: boolean;
        addholiday?: boolean;
        deleteholiday?: boolean;
        deleteschedule?: boolean;
        approvePostponeSchedule?: boolean;
    };
    webinar: {
        add?: boolean;
        update?: boolean;
        delete?: boolean;
        view?: boolean;
    };
    review: {
        view?: boolean;
        export?: boolean;
        add?: boolean;
        delete?: boolean;
        approve?: boolean;
    };
    feedback: {
        view?: boolean;
        export?: boolean;
        sendtoinstructor?: boolean;
        reply?: boolean;
    };
    coupon: {
        add?: boolean;
        delete?: boolean;
        view?: boolean;//viewall
        edit?: boolean;
        viewown?: boolean;
        approval?: boolean;
        export?: boolean;
    };
    subscription: {
        add?: boolean;
        edit?: boolean;
        view?: boolean;
        delete?: boolean;
        approval?: boolean;
    };
    messages: {
        viewownmessages?: boolean;
        viewallmessages?: boolean;
        replyownmessages?: boolean;
        replyallmessages?: boolean;
        export?: boolean;
        delete?: boolean;
    };
    announcements: {
        send?: boolean;
        delete?: boolean;
        view?: boolean;
        approval?: boolean;
        sendNotice?: boolean;
        deleteNotice?: boolean;
        approveNotice?: boolean;
    };
    notifications: {
        send?: boolean;
        delete?: boolean;
        view?: boolean;
        approval?: boolean;
    };
    product: {
        add?: boolean;
        edit?: boolean;
        view?: boolean;
        delete?: boolean;
        purchasehistory?: boolean;
        approval?: boolean;
        exportproduct?: boolean;
        exportpurchase?: boolean;
        changeexpiry?: boolean;
        CreateMentorshipSchedule?: boolean;
        ExportMentorshipSchedule?: boolean;
        ViewAllMentorshipSubscriptionDetails?: boolean;
        ViewOwnMentorshipSubscriptionDetails?: boolean;
        ExportMentorshipDetails?: boolean;
        ChangeMentorshipSchedule?: boolean;
        DeleteMentorshipSchedule?: boolean;
        AssignPortfolioCheckup?: boolean;
        ViewAllPortfolioCheckup?: boolean;
        ViewOwnPortfolioCheckup?: boolean;
        ExportPortfolioCheckup?: boolean;
        CreateLiveMarketPSchedule?: boolean;
        ExportLiveMarketPSchedule?: boolean;
        ChangeLiveMarketPSchedule?: boolean;
        ExportLiveMarketPDetails?: boolean;
        ViewAllLiveMarketPDetails?: boolean;
        ViewOwnLiveMarketPDetails?: boolean;
        DeleteLiveMarketPSchedule?: boolean;
        bookslots?: boolean;
        sendMarketResearch?: boolean;
        viewMarketResearch?: boolean;
        deleteMarketResearch?: boolean;
        approveMarketResearch?: boolean;
        exportMarketResearchDetails?: boolean;
        viewstocklist?: boolean;
        sendInvesletter?: boolean;
        viewInvesletter?: boolean;
        deleteInvesletter?: boolean;
        approveInvesletter?: boolean;
        viewFollowMyPortfolio?: boolean;
        manageFollowMyPortfolio?: boolean;
        exportFollowMyPortfolio?: boolean;
        sendWealthInsights?: boolean;
        viewWealthInsights?: boolean;
        deleteWealthInsights?: boolean;
        approveWealthInsights?: boolean;
        AddAwarnessVideos?: boolean;
        viewAwarnessVideos?: boolean;
        deleteAwarnessVideos?: boolean;
        approveAwarnessVideos?: boolean;
    };
    referrals: {
        viewreferrals?: boolean;
        viewtransactions?: boolean;
        addtransactions?: boolean;
        changestatus?: boolean;
        export?: boolean;
        settings?: boolean
    };
    devices: {
        viewdevices?: boolean;
        export?: boolean;
        settings?: boolean;
        viewloginhistory?: boolean;
        logoutusers?: boolean;
    };
    supports: {
        liveMarketSupportChat?: boolean
        settings?: boolean
        liveMarketSupportReport?: boolean
        export?: boolean;
    };
    students: {
        allcourseregdetails?: boolean;
        owncourseregdetails?: boolean;
        exportcourseregdetails?: boolean;
        addmanualreg?: boolean;
        viewmanualreg?: boolean;
        approvemanualreg?: boolean;
        exportmanualreg?: boolean;
        deletemanualreg?: boolean;
        updatestudentreg?: boolean;
        approveupdatestudentreg?: boolean;
        exportupdatestudentreg?: boolean;
        stulist?: boolean;
        exportstulist?: boolean;
        viewallmarks?: boolean;
        viewownmarks?: boolean;
        exportmarks?: boolean;
        approvecert?: boolean;
        rejectcert?: boolean;
        viewcert?: boolean;
        editstudent?: boolean;
        addstudent?: boolean;
        studentactivity?: boolean;
    };
    instructor: {
        viewlists?: boolean;
        viewprofile?: boolean;
        activate?: boolean;
        deactivate?: boolean;
        reject?: boolean;
        senddeactivationrequest?: boolean;
        readdeactivaterequest?: boolean;
        deletedeactivaterequest?: boolean;
        export?: boolean;
    };
    payments: {
        paymenthistory?: boolean;
        exportpaymenthistory?: boolean;
        partpaymenthistory?: boolean;
        exportpartpaymenthistory?: boolean;
        allaccountsstats?: boolean;
        ownaccountsstats?: boolean;
        exportaccounts?: boolean;
        createrefund?: boolean;
        viewallrefundhistory?: boolean;
        viewownrefundhistory?: boolean;
        exportrefundhistory?: boolean;
        banaccount?: boolean;
        viewbannedaccountlist?: boolean;
        exportbannedaccountlist?: boolean;
        viewleads?: boolean;
        exportleads?: boolean;
        gsthistory?: boolean;
        exportgsthistory?: boolean;
    };
    jobs: {
        post?: boolean;
        edit?: boolean;
        delete?: boolean;
        activate?: boolean;
        deactivate?: boolean;
        close?: boolean;
        open?: boolean;
        viewjob?: boolean;
        viewapplications?: boolean;
        exportapplications?: boolean;
    };
    adbanner: {
        add?: boolean;
        view?: boolean;
        delete?: boolean;
        approval?: boolean;
    };
    books: {
        add?: boolean;
        view?: boolean;
        delete?: boolean;
        approval?: boolean;
    };
    trainerKits: {
        add?: boolean;
        view?: boolean;
        delete?: boolean;
        approval?: boolean;
    };
    tutorial: {
        add?: boolean;
        edit?: boolean;
        view?: boolean;
        delete?: boolean;
        approval?: boolean;
    };
    employees: {
        createrole?: boolean;
        editrole?: boolean;
        viewrole?: boolean;
        addemployee?: boolean;
        updateemployeerole?: boolean;
        viewemployees?: boolean;
        exportemployee?: boolean;
        manageDepartments?: boolean;
        manageTeams?: boolean;
        manageDesignations?: boolean;
        editEmployee?: boolean;
        updateEmployeeAllocation?: boolean;
        vieworgchart?: boolean;
        changeEmployeePassword?: boolean;
    };
    sells: {
        createteam?: boolean;
        viewteam?: boolean;
        viewownteam?: boolean;
        editteam?: boolean;
        deleteteam?: boolean;
        exportteam?: boolean;
        viewownconversionlist?: boolean;
        viewallconversionlist?: boolean;
        viewteamsconversionlist?: boolean;
        exportconversionlist?: boolean;
        viewownsellsreport?: boolean;
        viewallsellsreport?: boolean;
        viewteammemssellsreport?: boolean;
        exportsellsreport?: boolean;
        viewallteamsellsreport?: boolean;
        viewownteamsellsreport?: boolean;
        exportteamsellsreport?: boolean;
        shortclose?: boolean;
        reopen?: boolean;
        tagemployee?: boolean;
        viewPl?: boolean;
        addPl?: boolean;
        exportPl?: boolean;
        addprojection?: boolean;
        editprojection?: boolean;
        viewownprojection?: boolean;
        viewteamsprojection?: boolean;
        approveprojection?: boolean;
        exportprojection?: boolean;
    };
    shorturl: {
        add?: boolean;
        update?: boolean;
        view?: boolean;
        delete?: boolean;
    };
    leads: {
        upload?: boolean;
        viewall?: boolean;
        viewown?: boolean;
        viewteams?: boolean;
        delete?: boolean;
        leadassign?: boolean;
        edit?: boolean;
        export?: boolean;
        addleadstatus?: boolean;
        addoccupation?: boolean;
        addleadsource?: boolean;
        viewallonboarding?: boolean;
        viewownonboarding?: boolean;
        viewteamsonboarding?: boolean;
        viewownleadsreport?: boolean;
        viewallleadsreport?: boolean;
        viewteammemsleadsreport?: boolean;
        exportleadsreport?: boolean;
        viewallteamleadsreport?: boolean;
        viewownteamleadsreport?: boolean;
        exportteamleadsreport?: boolean;
        addsupportcomment?: boolean;
        viewownonbtatreport?: boolean;
        viewteamsonbtatreport?: boolean;
        updatesettings?: boolean;
        managelevels?: boolean;
        promoteleads?: boolean;
        modifyStatus?: boolean;
        approveminimumprice?: boolean;
    };
    insignia: {
        approve?: boolean;
        add?: boolean;
        update?: boolean;
        view?: boolean;
        delete?: boolean;
        viewregistrations?: boolean;
        bookregistrations?: boolean;
        insigniareport?: boolean;
        temporarybanned?: boolean;
    };
    invesmentor: {
        approve?: boolean;
        add?: boolean;
        update?: boolean;
        view?: boolean;
        delete?: boolean;
        viewregistrations?: boolean;
    };
    reports: {
        bcmbreports?: boolean;
        ownbcmbreportins?: boolean;
        ivrreports?: boolean;
        ownivrreports?: boolean;
        owndeptivrreports?: boolean;
        ownteamivrreports?: boolean;
        appreports?: boolean;
    };
    attendanceleave: {
        approveAttendance?: boolean;
        exportAttendance?: boolean;
        viewAllAttendance?: boolean;
        viewTeamAttendance?: boolean;
        editAttendance?: boolean;
        approveRegularize?: boolean;
        exportRegularize?: boolean;
        viewAllRegularize?: boolean;
        viewTeamRegularize?: boolean;
        editRegularize?: boolean;
        deleteRegularize?: boolean;
        approveLeave?: boolean;
        exportLeave?: boolean;
        viewAllLeave?: boolean;
        viewTeamLeave?: boolean;
        deleteLeave?: boolean;
        addLeaveBalance?: boolean;
        manageLeavePolicy?: boolean;
        manageAttendanceSettings?: boolean;
        viewownteamroster?: boolean;
        viewallroster?: boolean;
        viewowndeptroster?: boolean;
        createroster?: boolean;
        deleteroster?: boolean;
        approveroster?: boolean;
    };
    orders: {
        viewAllOrder?: boolean;
        viewOwnOrder?: boolean;
        viewTeamOrder?: boolean;
        createOrder?: boolean;
        updateOrder?: boolean;
        modifyInstallment?: boolean;
        verifyInstallment?: boolean;
        requestAdjustment?: boolean;
        approveAdjustment?: boolean;
        shortClose?: boolean;
        requestRefund?: boolean;
        viewRefundList?: boolean;
        approveRefund?: boolean;
        approveBatchChange?: boolean;
        viewBatchChangeList?: boolean;
        requestBatchChange?: boolean;
        viewPaymentHistory?: boolean;
        changeCourseExpiry?: boolean;
        export?: boolean;
        addPayments?: boolean;
        cancelPaymentLink?: boolean;
    }
}